[tools]
init = "init" # Initialize
list = "list" # List todos
scan = "scan" # Scan codebase
delete = "delete" # Delete list
template = "template" # Templates sub
templateSave = "save" # template save
templateDelete = "deleteo" # template delete

[path]
templatesDir = "config/templates/"
visualDir = "config/visual/"
dataDir = "data/"
defaultsConfig = "config/default-init.toml"
projectsFile = "data/projects.toml"
projectsDir = "data/projects/"
