name = "default" #Name of preset

[sections]
header = true
task = true
number = true
priority = true
line = true
# separator is horizontal line between sections.
# --------------- like this
separator = false
# ~+~+~+~+~+~+~+~+ or this.
# in fact it may be anithing you can draw using letters.

[header]
separator = ""
prefix = "|> " # Yes, you need to set all spaces beforehand.
postfix = " todo:" # Here too
capitalized = false # By default it just leaves it as is.
# If true it will be "MY_AWESOME_APP"

[task]
separator = ""
prefix = "| ► "
postfix = "" # Leave it blank i you want.
capitalized = false 
# if ture it will be "FIX MEMORY LEAK"

[mumber]
separator = ""
prefix = ""
postfix = "."
before_priority = true # If false it would be [CRIT] 1.

[priority]
prefix = "["
postfix = "] "
capitalized = false
# if true it will be "[LOW]"

[line]
separator = ""
prefix = "|   → "
postfix = ""
number_prefix = ":"
number_postfix = ""
num_before_file = false

