# todo: color support
name = "minimal"
[Sections]
header = false
task = true
number = true
priority = true
line = true
separator = false
# You can even don't add separators to your skin
# Just set this to false and don't add them.

[Header] # Turned off, but still should be here.
prefix = ""
postfix = ""
capitalized = false

[Task]
prefix = ""
postfix = ""
capitalized = false

[Number]
prefix = ""
postfix = ". "
beforePriority = true

[Priority]
prefix = ""
postfix = " - " # No priority - no postfix)
capitalized = true # For better readability

[Line]
prefix = "- "
postfix = ""
numberPrefix = ":"
numberPostfix = ""
numBeforeFile = false
