[cmd]
help = "help"
init = "init"
scan = "scan"
list = "list"
delete = "delete"
rename = "rename"

[dir]
data = "~/.config/b3t/data/"
visual = "~/.config/b3t/visual/"
templates = "~/.config/b3t/templates/"

[env]
skin = "default"
template = "default"

[project]
init_file = "b3t.toml"
# project configuration file
scan_init = false 
# automatically init default project when scan new directory
init_scan = false
# automatically scans new projects.
autoignore = false
# automatically add b3t.toml to .gitignore
